#!/usr/bin/env ruby
# build_ml_set.rb
# Fragments the full entity-relation query by biolink type pairs,
# submits each to the Virtuoso SPARQL endpoint, and concatenates
# all results into a single CSV.
#
# Two extra columns are added for Disease entities:
#   canonical_entity1_uri / canonical_entity2_uri
# These map each disease to one of the 10 SIMPATHIC target diseases via the
# MONDO subclass hierarchy (generated by generate_canonical_lookup.rb).
# For non-Disease entities, and for diseases outside the 10-disease subtree,
# the canonical URI equals the exact URI (identity).

require 'sparql/client'
require 'csv'

ENDPOINT        = (ENV['SPARQL_ENDPOINT'] || 'http://localhost:8890/sparql').freeze
OUTPUT          = 'JUNE_all_pairs_both_orientations_split_evidence.csv.large'.freeze
CANONICAL_FILE  = 'canonical_disease.tsv'.freeze

BIOLINK = 'https://w3id.org/biolink/vocab/'.freeze
TYPES   = %w[Gene Protein Disease Phenotype Drug].freeze
PAIRS   = TYPES.permutation(2).to_a.freeze

# ---------------------------------------------------------------------------
# Load canonical disease lookup (generated by generate_canonical_lookup.rb).
# Falls back gracefully if the file doesn't exist yet.
# ---------------------------------------------------------------------------
CANONICAL = {}
if File.exist?(CANONICAL_FILE)
  CSV.foreach(CANONICAL_FILE, col_sep: "\t", headers: true) do |row|
    CANONICAL[row['specific_uri']] = row['canonical_uri']
  end
  puts "Loaded #{CANONICAL.size} canonical disease mappings from #{CANONICAL_FILE}"
else
  warn "WARNING: #{CANONICAL_FILE} not found — run generate_canonical_lookup.rb first."
  warn "         Canonical URIs will equal exact URIs (no subclass folding)."
end

def canonical_uri(uri, type)
  return uri unless type == 'Disease'
  CANONICAL[uri] || uri
end

# ---------------------------------------------------------------------------

def query_for(type1, type2)
  <<~SPARQL
    PREFIX simp:     <urn:simpathic:>
    PREFIX rdf:      <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
    PREFIX rdfs:     <http://www.w3.org/2000/01/rdf-schema#>
    PREFIX biolink:  <#{BIOLINK}>

    SELECT ?entity1 ?entity1_name (\"#{type1}\" AS ?entity1_type)
           ?entity2 ?entity2_name (\"#{type2}\" AS ?entity2_type)
           (GROUP_CONCAT(DISTINCT ?rel;    SEPARATOR=" | ") AS ?rels)
           (GROUP_CONCAT(DISTINCT ?source; SEPARATOR=" | ") AS ?sources)
           ?evidence
    WHERE {
      GRAPH ?graph {
        ?entity1 ?p      ?entity2 .
        ?entity1 a       biolink:#{type1} .
        ?entity2 a       biolink:#{type2} .
        ?entity1 rdfs:label ?entity1_name .
        ?entity2 rdfs:label ?entity2_name .
      }
      ?graph simp:source-relation ?rel .
      ?graph simp:skg-source      ?source .
      OPTIONAL { ?graph simp:evidence ?evidence . }
    }
    GROUP BY ?entity1 ?entity1_name ?entity2 ?entity2_name ?evidence
    ORDER BY ?entity1_name ?entity2_name
  SPARQL
end

client = SPARQL::Client.new(ENDPOINT, read_timeout: 3600)

COLUMNS = %w[
  entity1 entity1_name entity1_type
  entity2 entity2_name entity2_type
  rels sources evidence
  canonical_entity1_uri canonical_entity2_uri
].freeze

total_rows  = 0
header_done = false

CSV.open(OUTPUT, 'w', col_sep: "\t") do |csv|
  PAIRS.each_with_index do |(type1, type2), idx|
    label = "#{type1} → #{type2}"
    print "[#{idx + 1}/#{PAIRS.size}] #{label} ... "
    $stdout.flush

    begin
      results = client.query(query_for(type1, type2))
      rows    = results.to_a

      unless header_done
        csv << COLUMNS
        header_done = true
      end

      rows.each do |row|
        e1 = row[:entity1]&.to_s
        e2 = row[:entity2]&.to_s
        csv << [
          e1,
          row[:entity1_name]&.to_s,
          type1,
          e2,
          row[:entity2_name]&.to_s,
          type2,
          row[:rels]&.to_s,
          row[:sources]&.to_s,
          row[:evidence]&.to_s,
          canonical_uri(e1, type1),
          canonical_uri(e2, type2)
        ]
      end

      total_rows += rows.size
      puts "#{rows.size} rows"
    rescue StandardError => e
      warn "\n  ERROR on #{label}: #{e.message} — skipping"
      `echo "#{label}: #{e.message}" >> errors.log`
    end
  end
end

puts "\nDone — #{total_rows} total rows written to #{OUTPUT}"
puts "Run: wc -l #{OUTPUT}  (should be #{total_rows + 1} including header)"
